# Generated by Django 6.0 on 2025-12-20 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('folder_link', models.URLField(help_text='Paste the Google Drive folder share link here', max_length=500)),
                ('folder_id', models.CharField(blank=True, editable=False, help_text='Extracted from folder link', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
