# Generated by Django 6.0 on 2025-12-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='description',
            field=models.TextField(blank=True, help_text='Short emotional description or moment', null=True),
        ),
    ]
